global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["host.docker.internal:9093"]

scrape_configs:
  - job_name: "aws-node"
    static_configs:
      - targets: ["184.73.6.214:9100"]
